export { ORIGIN, SITE, PROFILES, OG_LOCALES, absolute, pageTitle } from './config'
export { canonical, alternates } from './urls'
export type { Alternate } from './urls'
export type { Crumb, PageSeo } from './types'
export * as schema from './schema'
